# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Leap < Formula
  desc ""
  homepage "https://github.com/ajilk/tools"
  version "1.0.43"
  depends_on :macos

  url "https://github.com/ajilk/leap/releases/download/v1.0.43/leap_Darwin.tar.gz"
  sha256 "5e9987991526c8945afce49aecb5dbf9add854485c4f350c20670d64ff40a68a"

  def install
    bin.install "leap"
  end

  if Hardware::CPU.arm?
    def caveats
      <<~EOS
        The darwin_arm64 architecture is not supported for the Leap
        formula at this time. The darwin_amd64 binary may work in compatibility
        mode, but it might not be fully supported.
      EOS
    end
  end
end
