# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Leap < Formula
  desc ""
  homepage "https://github.com/ajilk/tools"
  version "1.0.40"
  depends_on :macos

  url "https://github.com/ajilk/leap/releases/download/v1.0.40/leap_Darwin.tar.gz"
  sha256 "807124f7bd11735912ba24aeae5305a413a262f164b76c7ed0c6d30afa897cd8"

  def install
    bin.install "leap"
  end

  if Hardware::CPU.arm?
    def caveats
      <<~EOS
        The darwin_arm64 architecture is not supported for the Leap
        formula at this time. The darwin_amd64 binary may work in compatibility
        mode, but it might not be fully supported.
      EOS
    end
  end
end
